#pragma once

namespace tora_trader {
struct ReqUserLoginField;
struct RspUserLoginField;
struct RspInfoField;
struct UserLogoutField;
struct UserPasswordUpdateField;
struct ReqInputDeviceSerialField;
struct RspInputDeviceSerialField;
struct InputOrderField;
struct OrderField;
struct UserRefField;
struct TradeField;
struct InputOrderActionField;
struct InputCondOrderField;
struct ConditionOrderField;
struct InputCondOrderActionField;
struct InputNegoOrderField;
struct NegoOrderField;
struct NegoTradeField;
struct InputNegoOrderActionField;
struct InputOrderExField;
struct InputOrderActionExField;
struct MarketStatusField;
struct InputTransferFundField;
struct TransferFundField;
struct InputTransferPositionField;
struct TransferPositionField;
struct PeripheryTransferPositionField;
struct PeripheryTransferFundField;
struct ReqInquiryJZFundField;
struct RspInquiryJZFundField;
struct ReqInquiryBankAccountFundField;
struct RspInquiryBankAccountFundField;
struct TradingNoticeField;
struct ReqInquiryMaxOrderVolumeField;
struct RspInquiryMaxOrderVolumeField;
struct InquiryTradeConcentrationField;
struct ReqModifyOpenPosCostField;
struct InputNodeFundAssignmentField;
struct ReqInquiryNodeFundAssignmentField;
struct RspInquiryNodeFundAssignmentField;
struct QryExchangeField;
struct ExchangeField;
struct QrySecurityField;
struct SecurityField;
struct QryIPOInfoField;
struct IPOInfoField;
struct QryUserField;
struct UserField;
struct QryInvestorField;
struct InvestorField;
struct QryShareholderAccountField;
struct ShareholderAccountField;
struct QryRationalInfoField;
struct RationalInfoField;
struct QryOrderField;
struct QryOrderActionField;
struct OrderActionField;
struct QryTradeField;
struct QryTradingAccountField;
struct TradingAccountField;
struct QryPositionField;
struct PositionField;
struct QryTradingFeeField;
struct TradingFeeField;
struct QryInvestorTradingFeeField;
struct InvestorTradingFeeField;
struct QryIPOQuotaField;
struct IPOQuotaField;
struct QryOrderFundDetailField;
struct OrderFundDetailField;
struct QryFundTransferDetailField;
struct FundTransferDetailField;
struct QryPositionTransferDetailField;
struct PositionTransferDetailField;
struct QryPeripheryPositionTransferDetailField;
struct PeripheryPositionTransferDetailField;
struct QryPeripheryFundTransferDetailField;
struct PeripheryFundTransferDetailField;
struct QryBondConversionInfoField;
struct BondConversionInfoField;
struct QryBondPutbackInfoField;
struct BondPutbackInfoField;
struct QryInvestorCondOrderLimitParamField;
struct InvestorCondOrderLimitParamField;
struct QryConditionOrderField;
struct QryCondOrderActionField;
struct CondOrderActionField;
struct QryTradingNoticeField;
struct QryIPONumberResultField;
struct IPONumberResultField;
struct QryIPOMatchNumberResultField;
struct IPOMatchNumberResultField;
struct QryShareholderSpecPrivilegeField;
struct ShareholderSpecPrivilegeField;
struct QryMarketField;
struct MarketField;
struct QryETFFileField;
struct ETFFileField;
struct QryETFBasketField;
struct ETFBasketField;
struct QryInvestorPositionLimitField;
struct InvestorPositionLimitField;
struct QryImcParamsField;
struct ImcParamsField;
struct QryImcExchangeRateField;
struct ImcExchangeRateField;
struct QryHKPriceTickInfoField;
struct HKPriceTickInfoField;
struct QryLofFundInfoField;
struct LofFundInfoField;
struct QryPledgePositionField;
struct PledgePositionField;
struct QryPledgeInfoField;
struct PledgeInfoField;
struct QrySystemNodeInfoField;
struct SystemNodeInfoField;
struct QryStandardBondPositionField;
struct StandardBondPositionField;
struct QryPrematurityRepoOrderField;
struct PrematurityRepoOrderField;
struct QryNegoOrderField;
struct QryNegoOrderActionField;
struct NegoOrderActionField;
struct QryNegoTradeField;
struct QryNegotiationParamField;
struct NegotiationParamField;
struct QryPublicOfferedFundInfoField;
struct PublicOfferedFundInfoField;
struct QryPublicOfferedFundTradeDetailField;
struct PublicOfferedFundTradeDetailField;
struct QryTenderInfoField;
struct TenderInfoField;
struct QryAdditionalOfferingInfoField;
struct AdditionalOfferingInfoField;
struct QryAdditionalOfferingQuotaField;
struct AdditionalOfferingQuotaField;
struct ForceUserLogoutField;
struct ActivateUserField;
struct FensUserInfoField;
struct ConnectionInfoField;
}

#include "tora-rs/src/trader.rs.h"
#include "TORATstpTraderApi.h"
#include "rust/cxx.h"
#include <cstring>
#include <string>

namespace tora_trader {
using namespace TORASTOCKAPI;

class Converter {
public:
    static std::string GbkToUtf8(const char *src_str);
    static rust::String GbkToRustString(const char *src_str);
    static CTORATstpReqUserLoginField ReqUserLoginFieldToCpp(ReqUserLoginField x);
    static ReqUserLoginField CTORATstpReqUserLoginFieldToRust(CTORATstpReqUserLoginField* x);
    static CTORATstpRspUserLoginField RspUserLoginFieldToCpp(RspUserLoginField x);
    static RspUserLoginField CTORATstpRspUserLoginFieldToRust(CTORATstpRspUserLoginField* x);
    static CTORATstpRspInfoField RspInfoFieldToCpp(RspInfoField x);
    static RspInfoField CTORATstpRspInfoFieldToRust(CTORATstpRspInfoField* x);
    static CTORATstpUserLogoutField UserLogoutFieldToCpp(UserLogoutField x);
    static UserLogoutField CTORATstpUserLogoutFieldToRust(CTORATstpUserLogoutField* x);
    static CTORATstpUserPasswordUpdateField UserPasswordUpdateFieldToCpp(UserPasswordUpdateField x);
    static UserPasswordUpdateField CTORATstpUserPasswordUpdateFieldToRust(CTORATstpUserPasswordUpdateField* x);
    static CTORATstpReqInputDeviceSerialField ReqInputDeviceSerialFieldToCpp(ReqInputDeviceSerialField x);
    static ReqInputDeviceSerialField CTORATstpReqInputDeviceSerialFieldToRust(CTORATstpReqInputDeviceSerialField* x);
    static CTORATstpRspInputDeviceSerialField RspInputDeviceSerialFieldToCpp(RspInputDeviceSerialField x);
    static RspInputDeviceSerialField CTORATstpRspInputDeviceSerialFieldToRust(CTORATstpRspInputDeviceSerialField* x);
    static CTORATstpInputOrderField InputOrderFieldToCpp(InputOrderField x);
    static InputOrderField CTORATstpInputOrderFieldToRust(CTORATstpInputOrderField* x);
    static CTORATstpOrderField OrderFieldToCpp(OrderField x);
    static OrderField CTORATstpOrderFieldToRust(CTORATstpOrderField* x);
    static CTORATstpUserRefField UserRefFieldToCpp(UserRefField x);
    static UserRefField CTORATstpUserRefFieldToRust(CTORATstpUserRefField* x);
    static CTORATstpTradeField TradeFieldToCpp(TradeField x);
    static TradeField CTORATstpTradeFieldToRust(CTORATstpTradeField* x);
    static CTORATstpInputOrderActionField InputOrderActionFieldToCpp(InputOrderActionField x);
    static InputOrderActionField CTORATstpInputOrderActionFieldToRust(CTORATstpInputOrderActionField* x);
    static CTORATstpInputCondOrderField InputCondOrderFieldToCpp(InputCondOrderField x);
    static InputCondOrderField CTORATstpInputCondOrderFieldToRust(CTORATstpInputCondOrderField* x);
    static CTORATstpConditionOrderField ConditionOrderFieldToCpp(ConditionOrderField x);
    static ConditionOrderField CTORATstpConditionOrderFieldToRust(CTORATstpConditionOrderField* x);
    static CTORATstpInputCondOrderActionField InputCondOrderActionFieldToCpp(InputCondOrderActionField x);
    static InputCondOrderActionField CTORATstpInputCondOrderActionFieldToRust(CTORATstpInputCondOrderActionField* x);
    static CTORATstpInputNegoOrderField InputNegoOrderFieldToCpp(InputNegoOrderField x);
    static InputNegoOrderField CTORATstpInputNegoOrderFieldToRust(CTORATstpInputNegoOrderField* x);
    static CTORATstpNegoOrderField NegoOrderFieldToCpp(NegoOrderField x);
    static NegoOrderField CTORATstpNegoOrderFieldToRust(CTORATstpNegoOrderField* x);
    static CTORATstpNegoTradeField NegoTradeFieldToCpp(NegoTradeField x);
    static NegoTradeField CTORATstpNegoTradeFieldToRust(CTORATstpNegoTradeField* x);
    static CTORATstpInputNegoOrderActionField InputNegoOrderActionFieldToCpp(InputNegoOrderActionField x);
    static InputNegoOrderActionField CTORATstpInputNegoOrderActionFieldToRust(CTORATstpInputNegoOrderActionField* x);
    static CTORATstpInputOrderExField InputOrderExFieldToCpp(InputOrderExField x);
    static InputOrderExField CTORATstpInputOrderExFieldToRust(CTORATstpInputOrderExField* x);
    static CTORATstpInputOrderActionExField InputOrderActionExFieldToCpp(InputOrderActionExField x);
    static InputOrderActionExField CTORATstpInputOrderActionExFieldToRust(CTORATstpInputOrderActionExField* x);
    static CTORATstpMarketStatusField MarketStatusFieldToCpp(MarketStatusField x);
    static MarketStatusField CTORATstpMarketStatusFieldToRust(CTORATstpMarketStatusField* x);
    static CTORATstpInputTransferFundField InputTransferFundFieldToCpp(InputTransferFundField x);
    static InputTransferFundField CTORATstpInputTransferFundFieldToRust(CTORATstpInputTransferFundField* x);
    static CTORATstpTransferFundField TransferFundFieldToCpp(TransferFundField x);
    static TransferFundField CTORATstpTransferFundFieldToRust(CTORATstpTransferFundField* x);
    static CTORATstpInputTransferPositionField InputTransferPositionFieldToCpp(InputTransferPositionField x);
    static InputTransferPositionField CTORATstpInputTransferPositionFieldToRust(CTORATstpInputTransferPositionField* x);
    static CTORATstpTransferPositionField TransferPositionFieldToCpp(TransferPositionField x);
    static TransferPositionField CTORATstpTransferPositionFieldToRust(CTORATstpTransferPositionField* x);
    static CTORATstpPeripheryTransferPositionField PeripheryTransferPositionFieldToCpp(PeripheryTransferPositionField x);
    static PeripheryTransferPositionField CTORATstpPeripheryTransferPositionFieldToRust(CTORATstpPeripheryTransferPositionField* x);
    static CTORATstpPeripheryTransferFundField PeripheryTransferFundFieldToCpp(PeripheryTransferFundField x);
    static PeripheryTransferFundField CTORATstpPeripheryTransferFundFieldToRust(CTORATstpPeripheryTransferFundField* x);
    static CTORATstpReqInquiryJZFundField ReqInquiryJZFundFieldToCpp(ReqInquiryJZFundField x);
    static ReqInquiryJZFundField CTORATstpReqInquiryJZFundFieldToRust(CTORATstpReqInquiryJZFundField* x);
    static CTORATstpRspInquiryJZFundField RspInquiryJZFundFieldToCpp(RspInquiryJZFundField x);
    static RspInquiryJZFundField CTORATstpRspInquiryJZFundFieldToRust(CTORATstpRspInquiryJZFundField* x);
    static CTORATstpReqInquiryBankAccountFundField ReqInquiryBankAccountFundFieldToCpp(ReqInquiryBankAccountFundField x);
    static ReqInquiryBankAccountFundField CTORATstpReqInquiryBankAccountFundFieldToRust(CTORATstpReqInquiryBankAccountFundField* x);
    static CTORATstpRspInquiryBankAccountFundField RspInquiryBankAccountFundFieldToCpp(RspInquiryBankAccountFundField x);
    static RspInquiryBankAccountFundField CTORATstpRspInquiryBankAccountFundFieldToRust(CTORATstpRspInquiryBankAccountFundField* x);
    static CTORATstpTradingNoticeField TradingNoticeFieldToCpp(TradingNoticeField x);
    static TradingNoticeField CTORATstpTradingNoticeFieldToRust(CTORATstpTradingNoticeField* x);
    static CTORATstpReqInquiryMaxOrderVolumeField ReqInquiryMaxOrderVolumeFieldToCpp(ReqInquiryMaxOrderVolumeField x);
    static ReqInquiryMaxOrderVolumeField CTORATstpReqInquiryMaxOrderVolumeFieldToRust(CTORATstpReqInquiryMaxOrderVolumeField* x);
    static CTORATstpRspInquiryMaxOrderVolumeField RspInquiryMaxOrderVolumeFieldToCpp(RspInquiryMaxOrderVolumeField x);
    static RspInquiryMaxOrderVolumeField CTORATstpRspInquiryMaxOrderVolumeFieldToRust(CTORATstpRspInquiryMaxOrderVolumeField* x);
    static CTORATstpInquiryTradeConcentrationField InquiryTradeConcentrationFieldToCpp(InquiryTradeConcentrationField x);
    static InquiryTradeConcentrationField CTORATstpInquiryTradeConcentrationFieldToRust(CTORATstpInquiryTradeConcentrationField* x);
    static CTORATstpReqModifyOpenPosCostField ReqModifyOpenPosCostFieldToCpp(ReqModifyOpenPosCostField x);
    static ReqModifyOpenPosCostField CTORATstpReqModifyOpenPosCostFieldToRust(CTORATstpReqModifyOpenPosCostField* x);
    static CTORATstpInputNodeFundAssignmentField InputNodeFundAssignmentFieldToCpp(InputNodeFundAssignmentField x);
    static InputNodeFundAssignmentField CTORATstpInputNodeFundAssignmentFieldToRust(CTORATstpInputNodeFundAssignmentField* x);
    static CTORATstpReqInquiryNodeFundAssignmentField ReqInquiryNodeFundAssignmentFieldToCpp(ReqInquiryNodeFundAssignmentField x);
    static ReqInquiryNodeFundAssignmentField CTORATstpReqInquiryNodeFundAssignmentFieldToRust(CTORATstpReqInquiryNodeFundAssignmentField* x);
    static CTORATstpRspInquiryNodeFundAssignmentField RspInquiryNodeFundAssignmentFieldToCpp(RspInquiryNodeFundAssignmentField x);
    static RspInquiryNodeFundAssignmentField CTORATstpRspInquiryNodeFundAssignmentFieldToRust(CTORATstpRspInquiryNodeFundAssignmentField* x);
    static CTORATstpQryExchangeField QryExchangeFieldToCpp(QryExchangeField x);
    static QryExchangeField CTORATstpQryExchangeFieldToRust(CTORATstpQryExchangeField* x);
    static CTORATstpExchangeField ExchangeFieldToCpp(ExchangeField x);
    static ExchangeField CTORATstpExchangeFieldToRust(CTORATstpExchangeField* x);
    static CTORATstpQrySecurityField QrySecurityFieldToCpp(QrySecurityField x);
    static QrySecurityField CTORATstpQrySecurityFieldToRust(CTORATstpQrySecurityField* x);
    static CTORATstpSecurityField SecurityFieldToCpp(SecurityField x);
    static SecurityField CTORATstpSecurityFieldToRust(CTORATstpSecurityField* x);
    static CTORATstpQryIPOInfoField QryIPOInfoFieldToCpp(QryIPOInfoField x);
    static QryIPOInfoField CTORATstpQryIPOInfoFieldToRust(CTORATstpQryIPOInfoField* x);
    static CTORATstpIPOInfoField IPOInfoFieldToCpp(IPOInfoField x);
    static IPOInfoField CTORATstpIPOInfoFieldToRust(CTORATstpIPOInfoField* x);
    static CTORATstpQryUserField QryUserFieldToCpp(QryUserField x);
    static QryUserField CTORATstpQryUserFieldToRust(CTORATstpQryUserField* x);
    static CTORATstpUserField UserFieldToCpp(UserField x);
    static UserField CTORATstpUserFieldToRust(CTORATstpUserField* x);
    static CTORATstpQryInvestorField QryInvestorFieldToCpp(QryInvestorField x);
    static QryInvestorField CTORATstpQryInvestorFieldToRust(CTORATstpQryInvestorField* x);
    static CTORATstpInvestorField InvestorFieldToCpp(InvestorField x);
    static InvestorField CTORATstpInvestorFieldToRust(CTORATstpInvestorField* x);
    static CTORATstpQryShareholderAccountField QryShareholderAccountFieldToCpp(QryShareholderAccountField x);
    static QryShareholderAccountField CTORATstpQryShareholderAccountFieldToRust(CTORATstpQryShareholderAccountField* x);
    static CTORATstpShareholderAccountField ShareholderAccountFieldToCpp(ShareholderAccountField x);
    static ShareholderAccountField CTORATstpShareholderAccountFieldToRust(CTORATstpShareholderAccountField* x);
    static CTORATstpQryRationalInfoField QryRationalInfoFieldToCpp(QryRationalInfoField x);
    static QryRationalInfoField CTORATstpQryRationalInfoFieldToRust(CTORATstpQryRationalInfoField* x);
    static CTORATstpRationalInfoField RationalInfoFieldToCpp(RationalInfoField x);
    static RationalInfoField CTORATstpRationalInfoFieldToRust(CTORATstpRationalInfoField* x);
    static CTORATstpQryOrderField QryOrderFieldToCpp(QryOrderField x);
    static QryOrderField CTORATstpQryOrderFieldToRust(CTORATstpQryOrderField* x);
    static CTORATstpQryOrderActionField QryOrderActionFieldToCpp(QryOrderActionField x);
    static QryOrderActionField CTORATstpQryOrderActionFieldToRust(CTORATstpQryOrderActionField* x);
    static CTORATstpOrderActionField OrderActionFieldToCpp(OrderActionField x);
    static OrderActionField CTORATstpOrderActionFieldToRust(CTORATstpOrderActionField* x);
    static CTORATstpQryTradeField QryTradeFieldToCpp(QryTradeField x);
    static QryTradeField CTORATstpQryTradeFieldToRust(CTORATstpQryTradeField* x);
    static CTORATstpQryTradingAccountField QryTradingAccountFieldToCpp(QryTradingAccountField x);
    static QryTradingAccountField CTORATstpQryTradingAccountFieldToRust(CTORATstpQryTradingAccountField* x);
    static CTORATstpTradingAccountField TradingAccountFieldToCpp(TradingAccountField x);
    static TradingAccountField CTORATstpTradingAccountFieldToRust(CTORATstpTradingAccountField* x);
    static CTORATstpQryPositionField QryPositionFieldToCpp(QryPositionField x);
    static QryPositionField CTORATstpQryPositionFieldToRust(CTORATstpQryPositionField* x);
    static CTORATstpPositionField PositionFieldToCpp(PositionField x);
    static PositionField CTORATstpPositionFieldToRust(CTORATstpPositionField* x);
    static CTORATstpQryTradingFeeField QryTradingFeeFieldToCpp(QryTradingFeeField x);
    static QryTradingFeeField CTORATstpQryTradingFeeFieldToRust(CTORATstpQryTradingFeeField* x);
    static CTORATstpTradingFeeField TradingFeeFieldToCpp(TradingFeeField x);
    static TradingFeeField CTORATstpTradingFeeFieldToRust(CTORATstpTradingFeeField* x);
    static CTORATstpQryInvestorTradingFeeField QryInvestorTradingFeeFieldToCpp(QryInvestorTradingFeeField x);
    static QryInvestorTradingFeeField CTORATstpQryInvestorTradingFeeFieldToRust(CTORATstpQryInvestorTradingFeeField* x);
    static CTORATstpInvestorTradingFeeField InvestorTradingFeeFieldToCpp(InvestorTradingFeeField x);
    static InvestorTradingFeeField CTORATstpInvestorTradingFeeFieldToRust(CTORATstpInvestorTradingFeeField* x);
    static CTORATstpQryIPOQuotaField QryIPOQuotaFieldToCpp(QryIPOQuotaField x);
    static QryIPOQuotaField CTORATstpQryIPOQuotaFieldToRust(CTORATstpQryIPOQuotaField* x);
    static CTORATstpIPOQuotaField IPOQuotaFieldToCpp(IPOQuotaField x);
    static IPOQuotaField CTORATstpIPOQuotaFieldToRust(CTORATstpIPOQuotaField* x);
    static CTORATstpQryOrderFundDetailField QryOrderFundDetailFieldToCpp(QryOrderFundDetailField x);
    static QryOrderFundDetailField CTORATstpQryOrderFundDetailFieldToRust(CTORATstpQryOrderFundDetailField* x);
    static CTORATstpOrderFundDetailField OrderFundDetailFieldToCpp(OrderFundDetailField x);
    static OrderFundDetailField CTORATstpOrderFundDetailFieldToRust(CTORATstpOrderFundDetailField* x);
    static CTORATstpQryFundTransferDetailField QryFundTransferDetailFieldToCpp(QryFundTransferDetailField x);
    static QryFundTransferDetailField CTORATstpQryFundTransferDetailFieldToRust(CTORATstpQryFundTransferDetailField* x);
    static CTORATstpFundTransferDetailField FundTransferDetailFieldToCpp(FundTransferDetailField x);
    static FundTransferDetailField CTORATstpFundTransferDetailFieldToRust(CTORATstpFundTransferDetailField* x);
    static CTORATstpQryPositionTransferDetailField QryPositionTransferDetailFieldToCpp(QryPositionTransferDetailField x);
    static QryPositionTransferDetailField CTORATstpQryPositionTransferDetailFieldToRust(CTORATstpQryPositionTransferDetailField* x);
    static CTORATstpPositionTransferDetailField PositionTransferDetailFieldToCpp(PositionTransferDetailField x);
    static PositionTransferDetailField CTORATstpPositionTransferDetailFieldToRust(CTORATstpPositionTransferDetailField* x);
    static CTORATstpQryPeripheryPositionTransferDetailField QryPeripheryPositionTransferDetailFieldToCpp(QryPeripheryPositionTransferDetailField x);
    static QryPeripheryPositionTransferDetailField CTORATstpQryPeripheryPositionTransferDetailFieldToRust(CTORATstpQryPeripheryPositionTransferDetailField* x);
    static CTORATstpPeripheryPositionTransferDetailField PeripheryPositionTransferDetailFieldToCpp(PeripheryPositionTransferDetailField x);
    static PeripheryPositionTransferDetailField CTORATstpPeripheryPositionTransferDetailFieldToRust(CTORATstpPeripheryPositionTransferDetailField* x);
    static CTORATstpQryPeripheryFundTransferDetailField QryPeripheryFundTransferDetailFieldToCpp(QryPeripheryFundTransferDetailField x);
    static QryPeripheryFundTransferDetailField CTORATstpQryPeripheryFundTransferDetailFieldToRust(CTORATstpQryPeripheryFundTransferDetailField* x);
    static CTORATstpPeripheryFundTransferDetailField PeripheryFundTransferDetailFieldToCpp(PeripheryFundTransferDetailField x);
    static PeripheryFundTransferDetailField CTORATstpPeripheryFundTransferDetailFieldToRust(CTORATstpPeripheryFundTransferDetailField* x);
    static CTORATstpQryBondConversionInfoField QryBondConversionInfoFieldToCpp(QryBondConversionInfoField x);
    static QryBondConversionInfoField CTORATstpQryBondConversionInfoFieldToRust(CTORATstpQryBondConversionInfoField* x);
    static CTORATstpBondConversionInfoField BondConversionInfoFieldToCpp(BondConversionInfoField x);
    static BondConversionInfoField CTORATstpBondConversionInfoFieldToRust(CTORATstpBondConversionInfoField* x);
    static CTORATstpQryBondPutbackInfoField QryBondPutbackInfoFieldToCpp(QryBondPutbackInfoField x);
    static QryBondPutbackInfoField CTORATstpQryBondPutbackInfoFieldToRust(CTORATstpQryBondPutbackInfoField* x);
    static CTORATstpBondPutbackInfoField BondPutbackInfoFieldToCpp(BondPutbackInfoField x);
    static BondPutbackInfoField CTORATstpBondPutbackInfoFieldToRust(CTORATstpBondPutbackInfoField* x);
    static CTORATstpQryInvestorCondOrderLimitParamField QryInvestorCondOrderLimitParamFieldToCpp(QryInvestorCondOrderLimitParamField x);
    static QryInvestorCondOrderLimitParamField CTORATstpQryInvestorCondOrderLimitParamFieldToRust(CTORATstpQryInvestorCondOrderLimitParamField* x);
    static CTORATstpInvestorCondOrderLimitParamField InvestorCondOrderLimitParamFieldToCpp(InvestorCondOrderLimitParamField x);
    static InvestorCondOrderLimitParamField CTORATstpInvestorCondOrderLimitParamFieldToRust(CTORATstpInvestorCondOrderLimitParamField* x);
    static CTORATstpQryConditionOrderField QryConditionOrderFieldToCpp(QryConditionOrderField x);
    static QryConditionOrderField CTORATstpQryConditionOrderFieldToRust(CTORATstpQryConditionOrderField* x);
    static CTORATstpQryCondOrderActionField QryCondOrderActionFieldToCpp(QryCondOrderActionField x);
    static QryCondOrderActionField CTORATstpQryCondOrderActionFieldToRust(CTORATstpQryCondOrderActionField* x);
    static CTORATstpCondOrderActionField CondOrderActionFieldToCpp(CondOrderActionField x);
    static CondOrderActionField CTORATstpCondOrderActionFieldToRust(CTORATstpCondOrderActionField* x);
    static CTORATstpQryTradingNoticeField QryTradingNoticeFieldToCpp(QryTradingNoticeField x);
    static QryTradingNoticeField CTORATstpQryTradingNoticeFieldToRust(CTORATstpQryTradingNoticeField* x);
    static CTORATstpQryIPONumberResultField QryIPONumberResultFieldToCpp(QryIPONumberResultField x);
    static QryIPONumberResultField CTORATstpQryIPONumberResultFieldToRust(CTORATstpQryIPONumberResultField* x);
    static CTORATstpIPONumberResultField IPONumberResultFieldToCpp(IPONumberResultField x);
    static IPONumberResultField CTORATstpIPONumberResultFieldToRust(CTORATstpIPONumberResultField* x);
    static CTORATstpQryIPOMatchNumberResultField QryIPOMatchNumberResultFieldToCpp(QryIPOMatchNumberResultField x);
    static QryIPOMatchNumberResultField CTORATstpQryIPOMatchNumberResultFieldToRust(CTORATstpQryIPOMatchNumberResultField* x);
    static CTORATstpIPOMatchNumberResultField IPOMatchNumberResultFieldToCpp(IPOMatchNumberResultField x);
    static IPOMatchNumberResultField CTORATstpIPOMatchNumberResultFieldToRust(CTORATstpIPOMatchNumberResultField* x);
    static CTORATstpQryShareholderSpecPrivilegeField QryShareholderSpecPrivilegeFieldToCpp(QryShareholderSpecPrivilegeField x);
    static QryShareholderSpecPrivilegeField CTORATstpQryShareholderSpecPrivilegeFieldToRust(CTORATstpQryShareholderSpecPrivilegeField* x);
    static CTORATstpShareholderSpecPrivilegeField ShareholderSpecPrivilegeFieldToCpp(ShareholderSpecPrivilegeField x);
    static ShareholderSpecPrivilegeField CTORATstpShareholderSpecPrivilegeFieldToRust(CTORATstpShareholderSpecPrivilegeField* x);
    static CTORATstpQryMarketField QryMarketFieldToCpp(QryMarketField x);
    static QryMarketField CTORATstpQryMarketFieldToRust(CTORATstpQryMarketField* x);
    static CTORATstpMarketField MarketFieldToCpp(MarketField x);
    static MarketField CTORATstpMarketFieldToRust(CTORATstpMarketField* x);
    static CTORATstpQryETFFileField QryETFFileFieldToCpp(QryETFFileField x);
    static QryETFFileField CTORATstpQryETFFileFieldToRust(CTORATstpQryETFFileField* x);
    static CTORATstpETFFileField ETFFileFieldToCpp(ETFFileField x);
    static ETFFileField CTORATstpETFFileFieldToRust(CTORATstpETFFileField* x);
    static CTORATstpQryETFBasketField QryETFBasketFieldToCpp(QryETFBasketField x);
    static QryETFBasketField CTORATstpQryETFBasketFieldToRust(CTORATstpQryETFBasketField* x);
    static CTORATstpETFBasketField ETFBasketFieldToCpp(ETFBasketField x);
    static ETFBasketField CTORATstpETFBasketFieldToRust(CTORATstpETFBasketField* x);
    static CTORATstpQryInvestorPositionLimitField QryInvestorPositionLimitFieldToCpp(QryInvestorPositionLimitField x);
    static QryInvestorPositionLimitField CTORATstpQryInvestorPositionLimitFieldToRust(CTORATstpQryInvestorPositionLimitField* x);
    static CTORATstpInvestorPositionLimitField InvestorPositionLimitFieldToCpp(InvestorPositionLimitField x);
    static InvestorPositionLimitField CTORATstpInvestorPositionLimitFieldToRust(CTORATstpInvestorPositionLimitField* x);
    static CTORATstpQryImcParamsField QryImcParamsFieldToCpp(QryImcParamsField x);
    static QryImcParamsField CTORATstpQryImcParamsFieldToRust(CTORATstpQryImcParamsField* x);
    static CTORATstpImcParamsField ImcParamsFieldToCpp(ImcParamsField x);
    static ImcParamsField CTORATstpImcParamsFieldToRust(CTORATstpImcParamsField* x);
    static CTORATstpQryImcExchangeRateField QryImcExchangeRateFieldToCpp(QryImcExchangeRateField x);
    static QryImcExchangeRateField CTORATstpQryImcExchangeRateFieldToRust(CTORATstpQryImcExchangeRateField* x);
    static CTORATstpImcExchangeRateField ImcExchangeRateFieldToCpp(ImcExchangeRateField x);
    static ImcExchangeRateField CTORATstpImcExchangeRateFieldToRust(CTORATstpImcExchangeRateField* x);
    static CTORATstpQryHKPriceTickInfoField QryHKPriceTickInfoFieldToCpp(QryHKPriceTickInfoField x);
    static QryHKPriceTickInfoField CTORATstpQryHKPriceTickInfoFieldToRust(CTORATstpQryHKPriceTickInfoField* x);
    static CTORATstpHKPriceTickInfoField HKPriceTickInfoFieldToCpp(HKPriceTickInfoField x);
    static HKPriceTickInfoField CTORATstpHKPriceTickInfoFieldToRust(CTORATstpHKPriceTickInfoField* x);
    static CTORATstpQryLofFundInfoField QryLofFundInfoFieldToCpp(QryLofFundInfoField x);
    static QryLofFundInfoField CTORATstpQryLofFundInfoFieldToRust(CTORATstpQryLofFundInfoField* x);
    static CTORATstpLofFundInfoField LofFundInfoFieldToCpp(LofFundInfoField x);
    static LofFundInfoField CTORATstpLofFundInfoFieldToRust(CTORATstpLofFundInfoField* x);
    static CTORATstpQryPledgePositionField QryPledgePositionFieldToCpp(QryPledgePositionField x);
    static QryPledgePositionField CTORATstpQryPledgePositionFieldToRust(CTORATstpQryPledgePositionField* x);
    static CTORATstpPledgePositionField PledgePositionFieldToCpp(PledgePositionField x);
    static PledgePositionField CTORATstpPledgePositionFieldToRust(CTORATstpPledgePositionField* x);
    static CTORATstpQryPledgeInfoField QryPledgeInfoFieldToCpp(QryPledgeInfoField x);
    static QryPledgeInfoField CTORATstpQryPledgeInfoFieldToRust(CTORATstpQryPledgeInfoField* x);
    static CTORATstpPledgeInfoField PledgeInfoFieldToCpp(PledgeInfoField x);
    static PledgeInfoField CTORATstpPledgeInfoFieldToRust(CTORATstpPledgeInfoField* x);
    static CTORATstpQrySystemNodeInfoField QrySystemNodeInfoFieldToCpp(QrySystemNodeInfoField x);
    static QrySystemNodeInfoField CTORATstpQrySystemNodeInfoFieldToRust(CTORATstpQrySystemNodeInfoField* x);
    static CTORATstpSystemNodeInfoField SystemNodeInfoFieldToCpp(SystemNodeInfoField x);
    static SystemNodeInfoField CTORATstpSystemNodeInfoFieldToRust(CTORATstpSystemNodeInfoField* x);
    static CTORATstpQryStandardBondPositionField QryStandardBondPositionFieldToCpp(QryStandardBondPositionField x);
    static QryStandardBondPositionField CTORATstpQryStandardBondPositionFieldToRust(CTORATstpQryStandardBondPositionField* x);
    static CTORATstpStandardBondPositionField StandardBondPositionFieldToCpp(StandardBondPositionField x);
    static StandardBondPositionField CTORATstpStandardBondPositionFieldToRust(CTORATstpStandardBondPositionField* x);
    static CTORATstpQryPrematurityRepoOrderField QryPrematurityRepoOrderFieldToCpp(QryPrematurityRepoOrderField x);
    static QryPrematurityRepoOrderField CTORATstpQryPrematurityRepoOrderFieldToRust(CTORATstpQryPrematurityRepoOrderField* x);
    static CTORATstpPrematurityRepoOrderField PrematurityRepoOrderFieldToCpp(PrematurityRepoOrderField x);
    static PrematurityRepoOrderField CTORATstpPrematurityRepoOrderFieldToRust(CTORATstpPrematurityRepoOrderField* x);
    static CTORATstpQryNegoOrderField QryNegoOrderFieldToCpp(QryNegoOrderField x);
    static QryNegoOrderField CTORATstpQryNegoOrderFieldToRust(CTORATstpQryNegoOrderField* x);
    static CTORATstpQryNegoOrderActionField QryNegoOrderActionFieldToCpp(QryNegoOrderActionField x);
    static QryNegoOrderActionField CTORATstpQryNegoOrderActionFieldToRust(CTORATstpQryNegoOrderActionField* x);
    static CTORATstpNegoOrderActionField NegoOrderActionFieldToCpp(NegoOrderActionField x);
    static NegoOrderActionField CTORATstpNegoOrderActionFieldToRust(CTORATstpNegoOrderActionField* x);
    static CTORATstpQryNegoTradeField QryNegoTradeFieldToCpp(QryNegoTradeField x);
    static QryNegoTradeField CTORATstpQryNegoTradeFieldToRust(CTORATstpQryNegoTradeField* x);
    static CTORATstpQryNegotiationParamField QryNegotiationParamFieldToCpp(QryNegotiationParamField x);
    static QryNegotiationParamField CTORATstpQryNegotiationParamFieldToRust(CTORATstpQryNegotiationParamField* x);
    static CTORATstpNegotiationParamField NegotiationParamFieldToCpp(NegotiationParamField x);
    static NegotiationParamField CTORATstpNegotiationParamFieldToRust(CTORATstpNegotiationParamField* x);
    static CTORATstpQryPublicOfferedFundInfoField QryPublicOfferedFundInfoFieldToCpp(QryPublicOfferedFundInfoField x);
    static QryPublicOfferedFundInfoField CTORATstpQryPublicOfferedFundInfoFieldToRust(CTORATstpQryPublicOfferedFundInfoField* x);
    static CTORATstpPublicOfferedFundInfoField PublicOfferedFundInfoFieldToCpp(PublicOfferedFundInfoField x);
    static PublicOfferedFundInfoField CTORATstpPublicOfferedFundInfoFieldToRust(CTORATstpPublicOfferedFundInfoField* x);
    static CTORATstpQryPublicOfferedFundTradeDetailField QryPublicOfferedFundTradeDetailFieldToCpp(QryPublicOfferedFundTradeDetailField x);
    static QryPublicOfferedFundTradeDetailField CTORATstpQryPublicOfferedFundTradeDetailFieldToRust(CTORATstpQryPublicOfferedFundTradeDetailField* x);
    static CTORATstpPublicOfferedFundTradeDetailField PublicOfferedFundTradeDetailFieldToCpp(PublicOfferedFundTradeDetailField x);
    static PublicOfferedFundTradeDetailField CTORATstpPublicOfferedFundTradeDetailFieldToRust(CTORATstpPublicOfferedFundTradeDetailField* x);
    static CTORATstpQryTenderInfoField QryTenderInfoFieldToCpp(QryTenderInfoField x);
    static QryTenderInfoField CTORATstpQryTenderInfoFieldToRust(CTORATstpQryTenderInfoField* x);
    static CTORATstpTenderInfoField TenderInfoFieldToCpp(TenderInfoField x);
    static TenderInfoField CTORATstpTenderInfoFieldToRust(CTORATstpTenderInfoField* x);
    static CTORATstpQryAdditionalOfferingInfoField QryAdditionalOfferingInfoFieldToCpp(QryAdditionalOfferingInfoField x);
    static QryAdditionalOfferingInfoField CTORATstpQryAdditionalOfferingInfoFieldToRust(CTORATstpQryAdditionalOfferingInfoField* x);
    static CTORATstpAdditionalOfferingInfoField AdditionalOfferingInfoFieldToCpp(AdditionalOfferingInfoField x);
    static AdditionalOfferingInfoField CTORATstpAdditionalOfferingInfoFieldToRust(CTORATstpAdditionalOfferingInfoField* x);
    static CTORATstpQryAdditionalOfferingQuotaField QryAdditionalOfferingQuotaFieldToCpp(QryAdditionalOfferingQuotaField x);
    static QryAdditionalOfferingQuotaField CTORATstpQryAdditionalOfferingQuotaFieldToRust(CTORATstpQryAdditionalOfferingQuotaField* x);
    static CTORATstpAdditionalOfferingQuotaField AdditionalOfferingQuotaFieldToCpp(AdditionalOfferingQuotaField x);
    static AdditionalOfferingQuotaField CTORATstpAdditionalOfferingQuotaFieldToRust(CTORATstpAdditionalOfferingQuotaField* x);
    static CTORATstpForceUserLogoutField ForceUserLogoutFieldToCpp(ForceUserLogoutField x);
    static ForceUserLogoutField CTORATstpForceUserLogoutFieldToRust(CTORATstpForceUserLogoutField* x);
    static CTORATstpActivateUserField ActivateUserFieldToCpp(ActivateUserField x);
    static ActivateUserField CTORATstpActivateUserFieldToRust(CTORATstpActivateUserField* x);
    static CTORATstpFensUserInfoField FensUserInfoFieldToCpp(FensUserInfoField x);
    static FensUserInfoField CTORATstpFensUserInfoFieldToRust(CTORATstpFensUserInfoField* x);
    static CTORATstpConnectionInfoField ConnectionInfoFieldToCpp(ConnectionInfoField x);
    static ConnectionInfoField CTORATstpConnectionInfoFieldToRust(CTORATstpConnectionInfoField* x);
};
} // namespace tora_trader
